name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests and static analysis
    strategy:
      matrix:
        go: ["1.22.1"]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-bookworm
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Run tests
        run: go test

      - name: Run static analysis
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck
